language: node_js
sudo: required
env:
  global:
    - CODECOV_TOKEN: a55667d0-f8ac-4c68-9bb4-6685e475012d
cache:
  directories:
    - node_modules
node_js:
  - "node"
  - "10"
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pnew_password
  - sudo service mysql restart
  - sudo mysql -u root --default-character-set=utf8 -pnew_password < ./script/structure.sql
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
services:
  - mysql
  - redis-server

dist: xenial
